### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by JokaJukka** [SydMontague/ImageMaps#15]
When I load chunks with ImageMaps, this keeps spamming the console each tick:
`[18:19:07] [Server thread/INFO]: Send: Could not render map using renderer de.craftlancer.imagemaps.ImageMapRenderer
[18:19:07] [Server thread/ERROR]: Could not render map using renderer de.craftlancer.imagemaps.ImageMapRenderer
java.awt.AWTError: Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method) ~[?:1.8.0_241]
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65) ~[?:1.8.0_241]
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115) ~[?:1.8.0_241]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_241]
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74) ~[?:1.8.0_241]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_241]
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103) ~[?:1.8.0_241]
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82) ~[?:1.8.0_241]
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181) ~[?:1.8.0_241]
	at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:190) ~[patched_1.15.2.jar:git-Paper-366]
	at org.bukkit.craftbukkit.v1_15_R1.map.CraftMapCanvas.drawImage(CraftMapCanvas.java:72) ~[patched_1.15.2.jar:git-Paper-366]
	at de.craftlancer.imagemaps.ImageMapRenderer.render(ImageMapRenderer.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.map.CraftMapView.render(CraftMapView.java:158) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:465) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.WorldMap.a(WorldMap.java:342) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.ItemWorldMap.a(ItemWorldMap.java:339) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:95) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.EntityTrackerEntry.tick(EntityTrackerEntry.java:73) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:1986) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.g(PlayerChunkMap.java:1997) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:923) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:739) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:439) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-366]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[18:19:07] [Server thread/INFO]: Send: Could not render map using renderer de.craftlancer.imagemaps.ImageMapRenderer
[18:19:07] [Server thread/ERROR]: Could not render map using renderer de.craftlancer.imagemaps.ImageMapRenderer
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_241]
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103) ~[?:1.8.0_241]
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82) ~[?:1.8.0_241]
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181) ~[?:1.8.0_241]
	at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:190) ~[patched_1.15.2.jar:git-Paper-366]
	at org.bukkit.craftbukkit.v1_15_R1.map.CraftMapCanvas.drawImage(CraftMapCanvas.java:72) ~[patched_1.15.2.jar:git-Paper-366]
	at de.craftlancer.imagemaps.ImageMapRenderer.render(ImageMapRenderer.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.map.CraftMapView.render(CraftMapView.java:158) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.WorldMap$WorldMapHumanTracker.a(WorldMap.java:465) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.WorldMap.a(WorldMap.java:342) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.ItemWorldMap.a(ItemWorldMap.java:339) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:95) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.EntityTrackerEntry.tick(EntityTrackerEntry.java:73) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:1986) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.g(PlayerChunkMap.java:1997) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:923) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:739) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:439) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-366]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-366]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
`

Thanks for help.

**Comment by SydMontague** [comment]
The error states that Java wasn't able to connect to the X11 window server, which indicates that the issue is found within your server configuration, not the plugin itself.

Another user was able to resolve this issue by running `unset DISPLAY` a few years ago, so maybe that works for you as well.

Alternatively using the startup parameter `-Djava.awt.headless=true` might work as well.
