### ISSUE TITLE
Can't place image map

### ISSUE THREAD

**Issue by Peiprjs** [SydMontague/ImageMaps#34]
When I try to place an image map, it says "Map couldn't be placed, there is another entity in the way". I don't know why, it's clear. I've tried it in different sizes and options.

**Comment by SydMontague** [comment]
Is there anything in your server log, giving further information?

**Comment by Peiprjs** [comment]
Couldn't pass event PlayerInteractEvent to ImageMaps V1.0.6

**Comment by SydMontague** [comment]
Can you give me the full stacktrace?

**Comment by Peiprjs** [comment]
One second please

**Comment by Peiprjs** [comment]
[13:37:04] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:982) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1298) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:147) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:402) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:290) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge:?]
	... 23 more
[13:37:21] [Server thread/DEBUG] [net.minecraftforge.fml.FMLWorldPersistenceHook/WP]: Gathering id map for writing to world save world
[13:37:21] [Server thread/DEBUG] [net.minecraftforge.fml.FMLWorldPersistenceHook/WP]: ID Map collection complete world
[13:37:26] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /gamemode creative
[13:37:26] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Peipr: Set own game mode to Creative Mode]
[13:37:32] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /imagemap place BFSF_logo true false 5x5
[13:37:33] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:937) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1298) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:147) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:402) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:290) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge:?]
	... 23 more
[13:38:11] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /weather clear
[13:38:11] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [Peipr: Set the weather to clear]
[13:38:18] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /imagemap place BFSF_logo true false 1x1
[13:38:20] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:937) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1298) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:147) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:402) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:290) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge:?]
	... 23 more
[13:38:26] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /imagemap place BFSF_logo true false 1x1
[13:38:27] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:982) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1298) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:147) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:402) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:290) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge:?]
	... 23 more
[13:38:33] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /imagemap place BFSF_logo true false 1x1
[13:38:43] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:982) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1298) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:147) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:402) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:290) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge:?]
	... 23 more
[13:38:46] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /imagemap place BFSF_logo true false 1x1
[13:38:48] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:982) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1298) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:147) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:402) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:290) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge:?]
	... 23 more
[13:38:53] [Server thread/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://forge/org/bukkit/inventory/HorseInventory.class got resource org/bukkit/inventory/HorseInventory.class true
[13:39:15] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /imagemap ?
[13:39:19] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /imagemap list
[13:39:37] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Peipr issued server command: /imagemap place BFSF_logo false false 1x1
[13:39:39] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:982) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1298) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:147) ~[forge:f563167d-9c7acb6c-9fb885e8]
	at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:402) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
	at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:290) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge:?]
	... 23 more

**Comment by SydMontague** [comment]
This seems like a bug in your server software. According to the error it fails to create a map when the plugin requests it to, something that should never happen.

**Comment by Peiprjs** [comment]
Do you have any idea how that could be fixed?

**Comment by SydMontague** [comment]
I would recommend asking the provider of your server software. Some of their changes compared Spigot must've broken the Bukkit#createMap function in their implementation.

**Comment by Peiprjs** [comment]
Alright, thank you very much

**Comment by SydMontague** [comment]
An interesting development, the error is now happening on stock Spigot 1.17 (but not 1.16.5) due to a change in Mojang code...

https://hub.spigotmc.org/jira/browse/SPIGOT-6510
