### ISSUE TITLE
switching server worlds corrupts all maps and makes them empty.

### ISSUE THREAD

**Issue by Shizzins** [SydMontague/ImageMaps#41]
I own a server with multiple worlds and whenever I would switch them the maps end up getting corrupted and show nothing at all. Is there a fix to this?

**Comment by SydMontague** [comment]
How exactly are you switching the maps?

Maps are generally assigned to worlds, with the plugin creating them in the main world.

**Comment by dudepurple110** [comment]
@SydMontague I also have this problem. We're not switching the maps themselves. The problem is that whenever we switch to a different world on a server, all the images on the reloaded world would be corrupted; they would still be there but they're all invisible. Please fix </3

**Comment by zwollerob** [comment]
I suddenly get lots of error en all the images are gone... 
Not very happy to replace all 60 images or something :) 

```
[14:35:29] [Craft Scheduler Thread - 341/WARN]: [ImageMaps] Plugin ImageMaps v1.0.10 generated an exception while executing task 116548
java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106) ~[?:?]
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182) ~[?:?]
        at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:200) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at net.craftcitizen.imagemaps.ImageMapRenderer.lambda$render$1(ImageMapRenderer.java:63) ~[?:?]
        at net.craftcitizen.imagemaps.clcore.LambdaRunnable.run(LambdaRunnable.java:14) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3359-Spigot-dbf4938-4f5d59a]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.18-R0.1-SNAPSHOT.jar:3359-Spigot-dbf4938-4f5d59a]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by SydMontague** [comment]
@zwollerob your server seems to be missing some required software that allows Java to do its job.

**Comment by zwollerob** [comment]
> @zwollerob your server seems to be missing some required software that allows Java to do its job.

strange... everything worked fine but after updates of linux and a reboot it is killed... will look into it... you maybe know what the required software is? :)

**Comment by SydMontague** [comment]
Try starting your server with the ´-Djava.awt.headless=true´ parameter. This might help already.

Otherwise it's probably related to Xorg in some way, but I never had to deal with it myself I sadly lack knowledge of specifics.
