### ISSUE TITLE
Plugin wont load on latest 1.17.1

### ISSUE THREAD

**Issue by Zachdogg1** [SydMontague/ImageMaps#45]
When trying to enable this plugin on a server, the following issue is put into the startup log. 
`[20:52:10] [Server thread/INFO]: This server is running CraftBukkit version 3217-Bukkit-4f6bcc8 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[20:52:11] [Server thread/ERROR]: Could not load 'plugins/ImageMaps (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:147) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:393) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:398) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:227) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:295) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:143) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:143) ~[craftbukkit-1.17.1.jar:3217-Bukkit-4f6bcc8]
	... 7 more`
Its a bukkit 1.17.1 server, I have tried every 1.17 release of this plugin, all had the same issue

**Comment by Zachdogg1** [comment]
Nevermind was an issue with spigot
