### ISSUE TITLE
Could not pass player event interaction 

### ISSUE THREAD

**Issue by Aduxo** [SydMontague/ImageMaps#50]
Hello,

First of all, thank you for this great plugin !!

Since I've switched into Mohist, I have an issue when I try to place a new image.
Here is the error i get on the server console (see below)
I've tried with Imagemaps 1.0.10 AND 1.0.6 (last 1.16.5 release), but I have the same problem in both versions.
I precise that I have this error **only** when I create a new image and try to place it in the game (existing images that I have on the server are still working perfectly and I can place them too).
The image I tried to place is : https://i.ibb.co/fYMnzjK/m-sta-ctrb.png (buy I've tried with many other images. I've also copied existing images on the server and change their name to see if they're working as a new image, but no...)

Can you please help me ?
I'm using Mohist 1.16.5 version (I have a mods+plugins server)

Thank you so much!
Aduxo

```
`>.... [02:14:08 ERROR]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.10
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[forge:?]
at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1415) ~[?:?]
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1395) ~[forge:7e29f765-296df566-9fb885e8]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:237) ~[forge:7e29f765-296df566-9fb885e8]
at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:434) ~[?:?]
at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:289) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge:?]
... 23 more
>.... [02:14:28 ERROR]: Could not pass event PlayerInteractEvent to ImageMaps v1.0.10
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[forge:?]
at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:401) ~[?:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1415) ~[?:?]
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:1395) ~[forge:7e29f765-296df566-9fb885e8]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createMap(CraftServer.java:237) ~[forge:7e29f765-296df566-9fb885e8]
at net.craftcitizen.imagemaps.ImageMaps.getMapItem(ImageMaps.java:434) ~[?:?]
at net.craftcitizen.imagemaps.ImageMaps.placeImage(ImageMaps.java:360) ~[?:?]
at net.craftcitizen.imagemaps.ImageMaps.onInteract(ImageMaps.java:289) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge:?]
... 23 more`
```

**Comment by SydMontague** [comment]
This is a bug in your server software. It's running into an error when creating a new map, something it's never supposed to do.
