### ISSUE TITLE
Player near Image map triggers a warning

### ISSUE THREAD

**Issue by Tsoccerguy3** [SydMontague/ImageMaps#60]
Somethimes when a player gets close to a a imagemap it triggers this warming

[09:25:39 INFO]: GrizzlyTales issued server command: /warp Gladiator
[09:25:39 WARN]: [ImageMaps] Plugin ImageMaps v1.0.10 generated an exception while executing task 1396392
java.lang.IllegalStateException: Cache is already build or is currently being build
        at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.map.CraftMapColorCache.initCache(CraftMapColorCache.java:61) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.map.CraftMapColorCache.isCached(CraftMapColorCache.java:149) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.map.MapPalette.matchColor(MapPalette.java:247) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:215) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.craftcitizen.imagemaps.ImageMapRenderer.lambda$render$1(ImageMapRenderer.java:63) ~[ImageMaps.jar:?]
        at net.craftcitizen.imagemaps.clcore.LambdaRunnable.run(LambdaRunnable.java:14) ~[ImageMaps.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-307]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Tsoccerguy3** [comment]
fixed and closing
