### ISSUE TITLE
When players are near imagemaps Paper 1.19.4 has warnings

### ISSUE THREAD

**Issue by Tsoccerguy3** [SydMontague/ImageMaps#64]
[19:35:48 WARN]: [ImageMaps] Plugin ImageMaps v1.0.10 generated an exception while executing task 1027305
java.lang.IllegalStateException: Cache is already build or is currently being build
        at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.map.CraftMapColorCache.initCache(CraftMapColorCache.java:61) ~[paper-1.19.4.jar:git-Paper-516]
        at org.bukkit.craftbukkit.v1_19_R3.map.CraftMapColorCache.isCached(CraftMapColorCache.java:149) ~[paper-1.19.4.jar:git-Paper-516]
        at org.bukkit.map.MapPalette.matchColor(MapPalette.java:247) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:215) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.craftcitizen.imagemaps.ImageMapRenderer.lambda$render$1(ImageMapRenderer.java:63) ~[ImageMaps.jar:?]
        at net.craftcitizen.imagemaps.clcore.LambdaRunnable.run(LambdaRunnable.java:14) ~[ImageMaps.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-516]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-516]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Leahcimkrob** [comment]
Same issue:
[04:01:44] [Craft Scheduler Thread - 31 - ImageMaps/WARN]: [ImageMaps] Plugin ImageMaps v1.0.10 generated an exception while executing task 2957
java.lang.IllegalStateException: Cache is already build or is currently being build
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.map.CraftMapColorCache.initCache(CraftMapColorCache.java:61) ~[paper-1.19.4.jar:git-Paper-514]
	at org.bukkit.craftbukkit.v1_19_R3.map.CraftMapColorCache.isCached(CraftMapColorCache.java:149) ~[paper-1.19.4.jar:git-Paper-514]
	at org.bukkit.map.MapPalette.matchColor(MapPalette.java:247) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:215) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.craftcitizen.imagemaps.ImageMapRenderer.lambda$render$1(ImageMapRenderer.java:63) ~[ImageMaps.jar:?]
	at net.craftcitizen.imagemaps.clcore.LambdaRunnable.run(LambdaRunnable.java:14) ~[ImageMaps.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-514]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.4.jar:git-Paper-514]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by SydMontague** [comment]
Please try Version 1.0.11 whether that fixes the problem: https://github.com/SydMontague/ImageMaps/releases/tag/1.0.11

**Comment by Tsoccerguy3** [comment]
fixed and closing
