### ISSUE TITLE
Fix this error please :)

### ISSUE THREAD

**Issue by Therealalex1s** [SydMontague/ImageMaps#69]
Server version: Paper 1.20.4 latest build

[14:29:28 WARN]: [ImageMaps] Plugin ImageMaps v1.0.10 generated an exception while executing task 197463
java.lang.IllegalStateException: Cache is already build or is currently being build
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.map.CraftMapColorCache.initCache(CraftMapColorCache.java:61) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.map.CraftMapColorCache.isCached(CraftMapColorCache.java:149) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.map.MapPalette.matchColor(MapPalette.java:247) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.map.MapPalette.imageToBytes(MapPalette.java:215) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.craftcitizen.imagemaps.ImageMapRenderer.lambda$render$1(ImageMapRenderer.java:63) ~[ImageMaps.jar:?]
        at net.craftcitizen.imagemaps.clcore.LambdaRunnable.run(LambdaRunnable.java:14) ~[ImageMaps.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-497]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by SydMontague** [comment]
Please try [version 1.0.11](https://github.com/SydMontague/ImageMaps/releases/tag/1.0.11) and tell me whether it resolved your issue.
